title: Title of your CV site
profile_img: /assets/img/profile.jpg
icon_img: /assets/img/icon.png

name: "Bryan Condino"
job: "Database Developer"

phone_number: +639765978385
address: Marilao Bulacan, Philippines
email: bchengcondino@gmail.com
linkedin_username: https://www.linkedin.com/in/bryan-condino-92610a135/
github_username: bchengcondino
blog_url: https://bchengcondino.github.io/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
